name: Review translation PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "**/*.po"
      - "**/*.pot"

concurrency:
  group: po-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review-po-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: alyf-de/po-review-action@f40006d8450de7fd5b538e38603185bbee744117 # v1.3.0
